"""Create users table

Revision ID: 809e2f0676ef
Revises: None
Create Date: 2025-12-08 14:19:45.077687+00:00

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '809e2f0676ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###