"""create users table

Revision ID: 04a9d7f7b5a1
Revises: 2ef8938c0b54
Create Date: 2025-12-11 23:14:56.279788+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a9d7f7b5a1'
down_revision: Union[str, None] = '2ef8938c0b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###