"""Create users table

Revision ID: 8fea6e968541
Revises: 809e2f0676ef
Create Date: 2025-12-08 14:24:46.473894+00:00

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '8fea6e968541'
down_revision: Union[str, None] = '809e2f0676ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###