"""Create users table

Revision ID: 2ef8938c0b54
Revises: 3bc6480e78dd
Create Date: 2025-12-08 14:32:09.317034+00:00

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '2ef8938c0b54'
down_revision: Union[str, None] = '3bc6480e78dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###